version: "2.2"

services:
  mjpg-streamer:
    image: ${registry_host}/mjpg-streamer:${TAG}
    container_name: mjpg-streamer
    restart: unless-stopped
    mem_limit: 100M
    networks:
      - proxy
    devices:
      - /dev/vchiq
      - /dev/vcsm-cma
    expose:
      - 8080
    labels:
      - traefik.enable=true
      - traefik.http.services.webcam.loadbalancer.server.port=8080
      - traefik.http.routers.webcam.rule=PathPrefix(`/webcam`)
      - traefik.http.routers.webcam.entryPoints=web
      - traefik.http.routers.webcam.middlewares=webcam-strip,webcam-header
      - traefik.http.middlewares.webcam-strip.stripprefix.prefixes=/webcam
      - traefik.http.middlewares.webcam-strip.stripprefix.forceSlash=false
      - traefik.http.middlewares.webcam-header.headers.customrequestheaders.X-Script-Name=/webcam
      - com.centurylinklabs.watchtower.enable=true
networks:
  proxy:
    external: true
    name: ${proxy_network}
