version: "2.4"

services:
  mjpg-streamer:
    image: ${registry_host}/${registry_repository}/mjpg-streamer:${TAG}
    cpus: 0.25
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - TAG
        - gids
        - platform
